### ISSUE TITLE
404 on Dell T130 (idrac_redfish_config)

### ISSUE THREAD

**Issue by tholeb** [dell/redfish-ansible-module#114]
Hello, i'm writing this issue because i'm not sure what to do, I have the same problem as in issue #88 (404 cannot GET to '/redfish/v1/Managers/iDRAC.Embedded.1/Attributes').

From what I read it seems that the issue is caused because the server I use is a 13G(Dell T130) right ? But what can I do to apply Manager's settings with the redfish module (I'm doing it with the uri module and it works well, but i'm not a fan of it) ? 

Here is my `Ansible --version` :
```
ansible 2.9.10
  config file = /home/user/Ambox/.ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```
Here is a sample of what I want to apply to Managers :
```yaml
- name: Apply config
  idrac_redfish_config:
    category: Manager
    command: SetManagerAttributes
    manager_attribute_name: "{{ item.name }}"
    manager_attribute_value: "{{ item.value }}"
    baseuri: "{{ iDRAC_ip }}"
    username: "{{ username }}"
    password: "{{ password }}"
  loop:
    - name: "IPv4.1.Enable"
      value: "Enabled"
    - name: "NIC.1.VLanEnabled"
      value: "Disabled"
    - name: "NIC.1.VLanID"
      value: 1
```

Thank you.
