### ISSUE TITLE
DELL Redfish API to forward DELL R840 diagnostic logs as a syslog to syslog server

### ISSUE THREAD

**Issue by ashokbeh** [dell/redfish-ansible-module#115]
Hi,

Would appreciate if you can help on forwarding hardware diagnostic logs as a syslog to syslog server.
Is there any API available for iDRAC9 to perform this activity.

Regards
Ashok Behera

**Comment by anupamaloke** [comment]
@ashokbeh, you can add the syslog servers in iDRAC and iDRAC will forward the logs:

```
  - name: Enable Syslog and set Syslog servers in iDRAC
    community.general.idrac_redfish_config:
      category: Manager
      command: SetManagerAttributes
      resource_id: iDRAC.Embedded.1
      manager_attributes:
        SysLog.1.SysLogEnable: "Enabled"
        SysLog.1.Server1: "{{ syslog_server1 }}"
        SysLog.1.Server2: "{{ syslog_server2 }}"
      baseuri: "{{ idrac_ip}}"
      username: "{{ idrac_username}}"
      password: "{{ idrac_password }}" 
```
